### PR TITLE
changed API to get around show warnings

### PR DESCRIPTION
**Pull request by milktrader**
This is a fairly complex way around the issue, maybe too complex.

### CODE REVIEW

**Comment by milktrader** [comment]
This is how your API would change:

``` julia
julia> using ShowSet

julia> B = IntSet(5,2,6,11)
IntSet([2, 5, 6, 11])

julia> A = Set(["alpha", "beta", "gamma", "delta"])
Set(ASCIIString["alpha","gamma","delta","beta"])

julia> Pretty(B)
{2,5,6,11}

julia> Pretty(A)
{alpha,beta,delta,gamma}

julia> A = Pretty(Set(["alpha", "beta", "gamma", "delta"]))
{alpha,beta,delta,gamma}
```

**Comment by milktrader** [comment]
The `Pretty` type is a bit whimsical, of course you can call it whatever, if you even want to go this route to begin with :smile:

**Comment by scheinerman** [comment]
This is a clever idea, but not what I had hoped for because it would require one to use `Pretty` (or maybe we should call it `PrettySet`) to wrap our `Set` objects (in code that might already exist). I'm happy with the behavior my module provides and my only minor beef is with warning messages that warn me against something I wanted to do. 

I hope you don't mind, but I'd rather not fold in your changes. I saw elsewhere the idea of creating a macro that says `@nowarn`. I hope a Julia pro can create that!

**Comment by milktrader** [comment]
No problem not accepting this PR. It's your package!

I'll close it and we'll just leave this to posterity.

**Pull request closed without merging**
